---
#DaemonSet
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: lotus-miner
spec:
  selector:
    matchLabels:
      app: lotus
  template:
    metadata:
      name: lotus-miner
      labels:
        app: lotus
    spec:
      nodeSelector:
        app: miner
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: lotus-miner-pvc
          readOnly: false
      - name: paramcache
        persistentVolumeClaim:
          claimName: lotus-param-pvc
          readOnly: false
      containers:
      - name: lotus
        image: harbor.vimmer.top/library/lotus:uat
        imagePullPolicy: Always
        command: ["lotus"]
        args: ["daemon", "--bootstrap=false"]
        env:
          - name: LOTUS_PATH
            value: /home/file/final/lotus
          - name: FULLNODE_LISTEN_ADDR
            value: /ip4/0.0.0.0/tcp/1234/http
          - name: PROXY_FETCHER_ADDR
            value: ""
          - name: IPFS_GATEWAY
            value: https://proof-parameters.s3.cn-south-1.jdcloud-oss.com/ipfs/  
          - name: TMPDIR
            value: /home/file/final/tmp 
          - name: FIL_PROOFS_PARAMETER_CACHE
            value: /var/tmp/filecoin-proof-parameters  
        volumeMounts:
          - name: data
            mountPath: /home/file/final
          - name: paramcache
            mountPath: /var/tmp/filecoin-proof-parameters
      - name: lotus-storage-miner
        image: harbor.vimmer.top/library/lotus:uat
        imagePullPolicy: Always
        command: ["sh", "-c", "trap : TERM INT; (while true; do lotus-storage-miner run --nosync; done) & wait"]
        env:
          - name: LOTUS_PATH
            value: /home/file/final/lotus
          - name: LOTUS_STORAGE_PATH
            value: /home/file/final/lotusstorage
          - name: FULLNODE_LISTEN_ADDR
            value: /ip4/0.0.0.0/tcp/1234/http
          - name: IPFS_GATEWAY
            value: https://proof-parameters.s3.cn-south-1.jdcloud-oss.com/ipfs/
          - name: TMPDIR
            value: /home/file/final/tmp  
          - name: FIL_PROOFS_PARAMETER_CACHE
            value: /var/tmp/filecoin-proof-parameters  
        volumeMounts:
        - name: data
          mountPath: /home/file/final
        - name: paramcache
          mountPath: /var/tmp/filecoin-proof-parameters
---
#Service
apiVersion: v1
kind: Service
metadata:
  name: miner-svc
spec:
  selector:
    app: lotus-miner
  ports:
    - name: lotus-storage-miner
      protocol: TCP
      port: 2345
      targetPort: 2345

